version: '3.9'

services:
  frontend:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    command: npm run dev
  
  backend:
    build: 
      context: ./server/
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    command: python3 server.py