version: '3.9'

services:
  frontend:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
    command: python server.py
    ports:
      - "8000:8000"
    depends_on:
      - frontend